export const ICONS = {
  // Navigation & UI
  menu: "ri:menu-2-line",
  close: "ri:close-line",
  externalLink: "material-symbols:open-in-new",
  arrowRight: "material-symbols:arrow-forward",
  arrowLeft: "material-symbols:arrow-back",
  newspaper: "material-symbols:newspaper",
  bookOpen: "material-symbols:menu-book",
  location: "material-symbols:location-on-outline",
  calendar: "material-symbols:calendar-today-outline",
  download: "material-symbols:download",
  quote: "ri:double-quotes-l",
  sparkles: "material-symbols:auto-awesome",
  star: "ri:star-fill",
  starOutline: "ri:star-line",
  share: "material-symbols:share-outline",
  search: "material-symbols:search",
  info: "material-symbols:info-outline",
  sound: "material-symbols:volume-up-outline",
  soundOff: "material-symbols:volume-off-outline",

  // Social & Contacts
  email: "material-symbols:mail-outline",
  github: "simple-icons:github",
  linkedin: "simple-icons:linkedin",
  twitter: "simple-icons:x",
  resume: "material-symbols:description-outline",
  phone: "material-symbols:call-outline",

  // Technologies / Skills
  react: "simple-icons:react",
  nextjs: "simple-icons:nextdotjs",
  javascript: "simple-icons:javascript",
  typescript: "simple-icons:typescript",
  tailwindcss: "simple-icons:tailwindcss",
  bootstrap: "simple-icons:bootstrap",
  materialui: "simple-icons:mui",
  mantine: "simple-icons:mantine",
  radix: "simple-icons:radixui",
  shadcn: "simple-icons:shadcnui",
  nodejs: "simple-icons:nodedotjs",
  express: "simple-icons:express",
  restapi: "material-symbols:api",
  axios: "simple-icons:axios",
  prisma: "simple-icons:prisma",
  mongoose: "simple-icons:mongodb",
  sequelize: "simple-icons:sequelize",
  knex: "simple-icons:sqlite",
  typeorm: "simple-icons:typeorm",
  playwright: "simple-icons:playwright",
  vitest: "simple-icons:vitest",
  git: "simple-icons:git",
  vite: "simple-icons:vite",
  chatgpt: "simple-icons:openai",
  claude: "simple-icons:anthropic",
  aiAgent: "material-symbols:smart-toy-outline",
  antigravity: "simple-icons:google",
  codex: "material-symbols:terminal",
} as const;

export type IconName = keyof typeof ICONS;
