export const ICONS = {
  // Navigation & UI
  externalLink: "material-symbols:open-in-new",
  arrowRight: "material-symbols:arrow-forward",
  download: "material-symbols:download",

  // Social & Contacts
  email: "material-symbols:mail-outline",
  github: "simple-icons:github",
  linkedin: "simple-icons:linkedin",
  resume: "material-symbols:description-outline",
  phone: "material-symbols:call-outline",

  // Technologies / Skills
  react: "simple-icons:react",
  nextjs: "simple-icons:nextdotjs",
  javascript: "simple-icons:javascript",
  typescript: "simple-icons:typescript",
  html5: "simple-icons:html5",
  css: "simple-icons:css3",
  wordpress: "simple-icons:wordpress",
  redux: "simple-icons:redux",
  zustand: "simple-icons:zustand",
  tanstackquery: "simple-icons:reactquery",
  contextapi: "simple-icons:react",
  immutable: "simple-icons:immutable",
  tailwindcss: "simple-icons:tailwindcss",
  bootstrap: "simple-icons:bootstrap",
  materialui: "simple-icons:mui",
  mantine: "simple-icons:mantine",
  radix: "simple-icons:radixui",
  shadcn: "simple-icons:shadcnui",
  headlessui: "simple-icons:headlessui",
  nodejs: "simple-icons:nodedotjs",
  express: "simple-icons:express",
  restapi: "material-symbols:api",
  jwt: "simple-icons:jsonwebtokens",
  oauth: "material-symbols:security",
  mongodb: "simple-icons:mongodb",
  sql: "material-symbols:database",
  playwright: "simple-icons:playwright",
  vitest: "simple-icons:vitest",
  jest: "simple-icons:jest",
  reacttestinglibrary: "simple-icons:testinglibrary",
  accessibility: "material-symbols:accessibility-new",
  git: "simple-icons:git",
  githubactions: "simple-icons:githubactions",
  gitlab: "simple-icons:gitlab",
  svn: "simple-icons:subversion",
  vite: "simple-icons:vite",
  webpack: "simple-icons:webpack",
  babel: "simple-icons:babel",
  npm: "simple-icons:npm",
  vscode: "simple-icons:visualstudiocode",
  linear: "simple-icons:linear",
  chatgpt: "simple-icons:openai",
  claude: "simple-icons:anthropic",
  githubcopilot: "simple-icons:githubcopilot",
  aiAgent: "material-symbols:smart-toy-outline",
  antigravity: "simple-icons:google",
  codex: "material-symbols:terminal",
} as const;

export type IconName = keyof typeof ICONS;
